### PR TITLE
Remove --connection-token from ENTRYPOINT

### PR DESCRIPTION
**Pull request by anisimovdk**
## Description

New flag `--without-connection-token` was added to upstream , but it does not work with other flags (`--connection-token` or `--connection-token-file`) at the same time, so we need to remove `--connection-token` from entrypoint, and define flag in runtime.

## Related Issue(s)

[Make connection token in the server optional #136615](https://github.com/microsoft/vscode/issues/136615)

## Release Notes

```release-note
```

### CODE REVIEW

**Comment by jeanp413** [comment]
I think we should use `--without-connection-token` by default, if someone wants to use a token they can do so by modifying the Dockerfile.

**Comment by jeanp413** [comment]
@anisimovdk could you allow edits in the PR so I can push my changes or you could add `--without-connection-token` in the dockerfile :pray:

**Comment by anisimovdk** [comment]
> @anisimovdk could you allow edits in the PR so I can push my changes or you could add `--without-connection-token` in the dockerfile 🙏

Done

**Comment by jeanp413** [comment]
Thanks

**Pull request merged**
